
version: 2

models:
  - name: attractions_information
    # description: "A starter dbt model"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     tests:
    #       - unique
    #       - not_null

  - name: attractions_location
    # description: "A starter dbt model"
    # columns:
    #   - name: id
    #     description: "The primary key for this table"
    #     tests:
    #       - unique
    #       - not_null
